// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: table.proto

package go_micro_table

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Table service

type TableService interface {
	Create(ctx context.Context, in *Route, opts ...client.CallOption) (*CreateResponse, error)
	Delete(ctx context.Context, in *Route, opts ...client.CallOption) (*DeleteResponse, error)
	Update(ctx context.Context, in *Route, opts ...client.CallOption) (*UpdateResponse, error)
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*ListResponse, error)
	Lookup(ctx context.Context, in *LookupRequest, opts ...client.CallOption) (*LookupResponse, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...client.CallOption) (Table_WatchService, error)
}

type tableService struct {
	c    client.Client
	name string
}

func NewTableService(name string, c client.Client) TableService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.table"
	}
	return &tableService{
		c:    c,
		name: name,
	}
}

func (c *tableService) Create(ctx context.Context, in *Route, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.name, "Table.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableService) Delete(ctx context.Context, in *Route, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "Table.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableService) Update(ctx context.Context, in *Route, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "Table.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableService) List(ctx context.Context, in *Request, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "Table.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableService) Lookup(ctx context.Context, in *LookupRequest, opts ...client.CallOption) (*LookupResponse, error) {
	req := c.c.NewRequest(c.name, "Table.Lookup", in)
	out := new(LookupResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableService) Watch(ctx context.Context, in *WatchRequest, opts ...client.CallOption) (Table_WatchService, error) {
	req := c.c.NewRequest(c.name, "Table.Watch", &WatchRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &tableServiceWatch{stream}, nil
}

type Table_WatchService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*Event, error)
}

type tableServiceWatch struct {
	stream client.Stream
}

func (x *tableServiceWatch) Close() error {
	return x.stream.Close()
}

func (x *tableServiceWatch) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tableServiceWatch) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tableServiceWatch) Recv() (*Event, error) {
	m := new(Event)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Table service

type TableHandler interface {
	Create(context.Context, *Route, *CreateResponse) error
	Delete(context.Context, *Route, *DeleteResponse) error
	Update(context.Context, *Route, *UpdateResponse) error
	List(context.Context, *Request, *ListResponse) error
	Lookup(context.Context, *LookupRequest, *LookupResponse) error
	Watch(context.Context, *WatchRequest, Table_WatchStream) error
}

func RegisterTableHandler(s server.Server, hdlr TableHandler, opts ...server.HandlerOption) error {
	type table interface {
		Create(ctx context.Context, in *Route, out *CreateResponse) error
		Delete(ctx context.Context, in *Route, out *DeleteResponse) error
		Update(ctx context.Context, in *Route, out *UpdateResponse) error
		List(ctx context.Context, in *Request, out *ListResponse) error
		Lookup(ctx context.Context, in *LookupRequest, out *LookupResponse) error
		Watch(ctx context.Context, stream server.Stream) error
	}
	type Table struct {
		table
	}
	h := &tableHandler{hdlr}
	return s.Handle(s.NewHandler(&Table{h}, opts...))
}

type tableHandler struct {
	TableHandler
}

func (h *tableHandler) Create(ctx context.Context, in *Route, out *CreateResponse) error {
	return h.TableHandler.Create(ctx, in, out)
}

func (h *tableHandler) Delete(ctx context.Context, in *Route, out *DeleteResponse) error {
	return h.TableHandler.Delete(ctx, in, out)
}

func (h *tableHandler) Update(ctx context.Context, in *Route, out *UpdateResponse) error {
	return h.TableHandler.Update(ctx, in, out)
}

func (h *tableHandler) List(ctx context.Context, in *Request, out *ListResponse) error {
	return h.TableHandler.List(ctx, in, out)
}

func (h *tableHandler) Lookup(ctx context.Context, in *LookupRequest, out *LookupResponse) error {
	return h.TableHandler.Lookup(ctx, in, out)
}

func (h *tableHandler) Watch(ctx context.Context, stream server.Stream) error {
	m := new(WatchRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TableHandler.Watch(ctx, m, &tableWatchStream{stream})
}

type Table_WatchStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Event) error
}

type tableWatchStream struct {
	stream server.Stream
}

func (x *tableWatchStream) Close() error {
	return x.stream.Close()
}

func (x *tableWatchStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tableWatchStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tableWatchStream) Send(m *Event) error {
	return x.stream.Send(m)
}
